const mongoose=require("mongoose");
const backenddataSchema=new mongoose.Schema({
    id:{
        type:Number,
        required:true
    },
    catdivd:{
        type:String,
        required:true
    },
    nameofthecourse:{
        type:String,
        required:true
    },
    imgsrc:{
        type:String,
        required:true
    },
    date:{
        type:String,
        required:true
    },
    cat1:{
        type:String,
        required:true
    },
    participants:{
        type:Number,
        required:true
    },
    cat2:{
        type:String,
        required:true
    },
    duration:{
        type:String,
        required:true
    },
    cat3:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },

})
const backendSchema=mongoose.model('backenddata', backenddataSchema);
module.exports={backendSchema}